services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.15.0
    env_file:
      - .env.production  # Pass the Node.js version as a build argument.
    restart: unless-stopped  # Ensure the container restarts unless explicitly stopped.
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container for development purposes.
